FROM node:14-alpine AS builder
WORKDIR /usr/src/app
COPY . /usr/src/app
ENV NODE_ENV=production
RUN npm i --quiet --only=production

FROM node:14-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app /usr/src/app
RUN npm run build
CMD npm run start