# Generated by Django 4.2 on 2023-05-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='preview_image_url',
        ),
    ]
