# Generated by Django 4.2 on 2023-05-05 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_remove_widget_preview_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
