# Generated by Django 4.2 on 2023-05-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_widget_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='widget',
            table='widget',
        ),
    ]
