# Generated by Django 4.2 on 2023-05-07 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_alter_widget_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
