# Generated by Django 4.2 on 2023-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_alter_widget_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='click_cta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='full_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='open_widget',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='unique_watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
