version: "3.8"

services:
  backend:
    restart: always
    build:
      context: ../backend
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
      - celery
    volumes:
      - /static:/static
      - ../backend/:/app

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:13.4-alpine"
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile.celery
    command: celery -A config worker -B -l INFO
    volumes:
      - /static:/static
      - ../backend/:/app
    depends_on:
      - redis

    

  # client:
  #   build: ../client
  #   volumes:
  #     - ./client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
