  GNU nano 2.9.8                                                                                          docker-compose.yml

version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static-backend/
      - media_value:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - client

  backend:
    restart: unless-stopped
    image: trywidget/trywidget_backend:v1
    env_file:
      - .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    command: >
      sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres
      - redis
      - celery

  celery:
    image: trywidget/trywidget_celery:v1
    command: celery -A config worker -B -l INFO
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

  postgres:
    restart: always
    image: postgres:13-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  client:
    restart: unless-stopped
    image: trywidget/trywidget_client:v1
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
  redis_data: