# Generated by Django 4.2 on 2023-05-01 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_payment_date', models.DateTimeField(null=True)),
                ('trial_end', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 9, 2, 9, 596114, tzinfo=datetime.timezone.utc))),
                ('visit_count', models.IntegerField(default=0)),
                ('last_login_at', models.DateTimeField(auto_now_add=True)),
                ('email_verify_token', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
