# Generated by Django 4.2 on 2023-05-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plans_save'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plans',
            table='plan',
        ),
        migrations.AlterModelTable(
            name='userplan',
            table='user_plan',
        ),
    ]
