# Generated by Django 4.2 on 2023-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plans_table_alter_userplan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='time_period',
            field=models.IntegerField(choices=[('month', 'month'), ('year', 'year')]),
        ),
    ]
