# Generated by Django 4.2 on 2023-05-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payments_payment_id'),
        ('plans', '0005_alter_userplan_time_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
