# Generated by Django 4.2 on 2023-05-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='payment',
        ),
    ]
