# Generated by Django 4.2 on 2023-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(max_length=256),
        ),
    ]
