name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
      - uses: actions/checkout@v1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd trywidget-master && git checkout production -f && git pull origin HEAD && docker-compose -f ./devops/docker-compose.prod.yml up -d --build --remove-orphans

